### ISSUE TITLE
drat deployment failing

### ISSUE THREAD

**Issue by jakejh** [hugheylab/tipa#2]
I'm not sure why, but it says the tarball is not found. Check out the latest CircleCI report. @JSchoenbachler Can you work on this?

https://github.com/hugheylab/tipa/blob/e8583cf73256920183d476c285f5af138e473c4c/.circleci/config.yml#L117

**Comment by JSchoenbachler** [comment]
I fixed this in the most recent push-

https://github.com/hugheylab/tipa/commit/ebed80cae71a6f44a1bcf42e995ff25993590e10

I was changing and cloning directories where I shouldn't have been. I will fix on the other packages as well
